package com.chainsys.collection;

import java.util.ArrayList;
import java.util.Collections;
import java.util.LinkedList;
import java.util.Stack;
import java.util.Vector;

public class CsProgram1 {
	public static void main(String[] args) {
		System.out.println("ArrayList Implementation");
		System.out.println(" ");
		ArrayList al = new ArrayList();
		for (int i = 0; i <= 6; i++)
			al.add(i);
		System.out.println(al);
		System.out.println("Add");
		al.add(1, "Suki");
		System.out.println(al);
		System.out.println("Remove");
		al.remove(2);
		System.out.println(al);
		System.out.println("Get");
		System.out.println(al.get(1));
		System.out.println("Set");
		al.set(0, "Angelin");
		System.out.println(al);
		System.out.println("Clone");
		al.clone();
		System.out.println(al);
		System.out.println("Sublist");
		al.subList(0, 2);
		System.out.println(al);
		System.out.println(" ");
		System.out.println("----------------------------------------------");
		System.out.println(" ");

		System.out.println("LinkedList Implementation");
		System.out.println(" ");
		LinkedList<String> ll = new LinkedList<String>();
		System.out.println("Add");
		ll.add("Angelin");
		System.out.println(ll);
		System.out.println("Index");
		ll.add(1, "Sukirtha");
		System.out.println(ll);
		System.out.println("Add First");
		ll.addFirst("Rithi");
		System.out.println(ll);
		System.out.println("Add Last");
		ll.addLast("Poorna");
		System.out.println(ll);
		System.out.println("Hashcode");
		ll.hashCode();
		System.out.println(ll);
		System.out.println("Pop");
		ll.pop();
		System.out.println(ll);
		System.out.println("Push");
		ll.push("Sneka");
		System.out.println(ll);
		System.out.println("Remove");
		ll.remove();
		System.out.println(ll);
		System.out.println("Remove First");
		ll.removeFirst();
		System.out.println(ll);
		System.out.println("Remove Last");
		ll.removeLast();
		System.out.println(ll);
		System.out.println("Clear");
		ll.clear();
		System.out.println(ll);
		System.out.println("Empty");
		System.out.println(ll.isEmpty());
		System.out.println(" ");
		System.out.println("----------------------------------------------");
		System.out.println(" ");

		System.out.println("Vector Implementation");
		System.out.println(" ");
		Vector<Integer> v = new Vector<Integer>();
		System.out.println("Add");
		v.add(0);
		System.out.println(v);
		v.add(1, 3);
		v.add(2, 3);
		v.add(3, 3);
		v.add(4, 3);
		v.add(5, 3);
		System.out.println(v);
		System.out.println("Clone");
		v.clone();
		System.out.println(v);
		System.out.println("Get");
		System.out.println(v.get(1));
		System.out.println("Set");
		v.set(4, 4);
		System.out.println(v);
		System.out.println("Hashcode");
		v.hashCode();
		System.out.println(v);
		System.out.println("Empty");
		System.out.println(v.isEmpty());
		System.out.println(" ");
		System.out.println("----------------------------------------------");
		System.out.println(" ");

		System.out.println("Stack Implementation");
		Stack<Integer> s = new Stack<Integer>();
		System.out.println("Add");
		s.add(45);
		System.out.println(s);
		s.add(1, 56);
		s.add(2, 23);
		s.add(3, 12);
		s.add(4, 87);
		System.out.println(s);
		System.out.println(s.isEmpty());
		System.out.println("Index Of");
		System.out.println(s.indexOf(56));
		System.out.println(" ");
		System.out.println("----------------------------------------------");
		System.out.println(" ");	
	}
}
